version: '3.3'
services:
    web-random:
        build:
            context: .
            args:
                requirements: ./requirements.txt
        image: shik1801/image3:part7
        environment:
            MONGO_HOST: mongo
        ports:
            - "5000:5000"
        entrypoint: python ./app.py
        depends_on:
            - mongo

    mongo:
        image: mongo
        volumes:
          - mongodb_data:/data/db
        ports:
            - "27017:27017"
volumes:
  mongodb_data: